### PR TITLE
Setup workflow to sync with upstream docs

### PR DESCRIPTION
**Pull request by frostming**
This PR sets up a GitHub action to sync with upstream periodically(per hour) and generates translation files in case there are any changes with the `docs/` folder.

### CODE REVIEW

**Comment by greyli** [comment]
It's very useful! Some thoughts on this workflow:

- Create an issue after the sync finished, so people can update the related translation.
- The upstream branch to merge should be 2.0.x (when the whole translation finished, we will create a 2.0.x in this repo).

By the way, I'm not sure if per hour is too frequent, we can update the frequency if needed later.

**Comment by frostming** [comment]
> Create an issue after the sync finished, so people can update the related translation.

Good suggestion, will update later

> I'm not sure if per hour is too frequent, we can update the frequency if needed later.

Yes, per day should be enough, runs at 3am UTF+8 or so?

**Comment by greyli** [comment]
> Yes, per day should be enough, runs at 3am UTF+8 or so?

Sounds good.

**Comment by frostming** [comment]
I created a step to create issue with Python scripts, I don't know if you are okay with the approach.

**Comment by greyli** [comment]
Looks good. Let's get this running first ;)

**Comment by frostming** [comment]
呃，发现个小问题，我直接在main上修改了

**Pull request merged**
